language: generic

sudo: true
dist: trusty

install:
  - sudo apt-get --yes install snapd
  - sudo apt-get --yes install hugo
  - sudo apt-get install python3-pygments
  - git clone --recursive -j8 https://github.com/alexandschaefer/alexandschaefer.github.io.git
  - git clone --recursive -j8 https://github.com/alexandschaefer/blog.git
  - cd blog

script:
  - hugo
  - cd public
  - ls -la
  - mv * ../alexandschaefer.github.io/
  - cd ../alexandschaefer.github.io/

deploy:
  repo: alexandschaefer/alexandschaefer.github.io
  target_branch: master
  provider: pages
  skip_cleanup: true
  github_token: $deploy_token
  on:
    branch: master
